version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: /api
        REACT_APP_BACKEND_URL: /
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    # ❌ TIDAK expose ke luar
    env_file: ./backend/.env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/chemical-discovery
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ML_SERVICE_URL=http://ml-service:5000
      - CLIENT_URL=http://157.15.40.59
    volumes:
      - backend_images:/app/public/images
    depends_on:
      - mongodb
      - redis
      - ml-service
    restart: unless-stopped

  ml-service:
    build: ./ml-service
    expose:
      - "5000"
    env_file: ./ml-service/.env
    environment:
      - FLASK_ENV=production
      - BACKEND_URL=http://backend:3010
    restart: unless-stopped

  mongodb:
    image: mongo:7
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  backend_images: